---
apiVersion: operator.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: cnv-mirrorset-5-0
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/openshift-virtualization/konflux-builds/v5-0
    source: registry.redhat.io/container-native-virtualization
