---
apiVersion: operator.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: cnv-mirrorset
spec:
  imageDigestMirrors:
  - mirrors:
    - brew.registry.redhat.io/container-native-virtualization
    - quay.io/openshift-virtualization/konflux-builds/v5-99
    - quay.io/openshift-virtualization/konflux-builds/v4-99
    - quay.io/openshift-virtualization/konflux-builds/v4-22
    - quay.io/openshift-virtualization/konflux-builds/v4-21
    - quay.io/openshift-virtualization/konflux-builds/v4-20
    - quay.io/openshift-virtualization/konflux-builds/v4-19
    - quay.io/openshift-virtualization/konflux-builds/v4-18
    - quay.io/openshift-virtualization/konflux-builds/v4-17
    - quay.io/openshift-virtualization/konflux-builds/v4-16
    - quay.io/openshift-virtualization/konflux-builds/v4-15
    - quay.io/openshift-virtualization/konflux-builds/v4-14
    - quay.io/openshift-virtualization/konflux-builds/v4-13
    - quay.io/openshift-virtualization/konflux-builds/v4-12
    source: registry.redhat.io/container-native-virtualization