---
apiVersion: operator.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: cnv-mirrorset-4-20
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/openshift-virtualization/konflux-builds/v4-20
    source: registry.redhat.io/container-native-virtualization
