name: Sanity Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Sanity Checks
    runs-on: ubuntu-latest
    env:
      OPM_VERSION: v1.39.0

    steps:
      - uses: actions/checkout@v3

      - name: Prepare auth file
        run: echo ${AUTH_FILE_CONTENT} | base64 -d > ${REGISTRY_AUTH_FILE}
        env:
          AUTH_FILE_CONTENT: ${{ secrets.BREW_AUTH }}
          REGISTRY_AUTH_FILE: ./auth.json

      - name: Get opm client
        run: |
          wget https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm
          chmod +x linux-amd64-opm
          mkdir -p .docker
          cp auth.json .docker/config.json

      - name: Do sanity checks
        run: make sanity-brew
        env:
          REGISTRY_AUTH_FILE: ./auth.json
          SKOPEO_CMD: podman run --rm -v .:/auth quay.io/skopeo/stable:latest
          AUTH_FILE: --authfile=/auth/auth.json
          OPM_CMD: ./linux-amd64-opm
          DOCKER_CONFIG: .docker/
